-- AlterTable
ALTER TABLE `Customers` MODIFY `createdAt` DATETIME(6) NOT NULL DEFAULT (NOW() + INTERVAL 3 HOUR);

-- AlterTable
ALTER TABLE `Payments` MODIFY `createdAt` DATETIME(6) NOT NULL DEFAULT (NOW() + INTERVAL 3 HOUR);

-- AlterTable
ALTER TABLE `Users` MODIFY `createdAt` DATETIME(6) NOT NULL DEFAULT (NOW() + INTERVAL 3 HOUR);
