-- AlterTable
ALTER TABLE `Customers` MODIFY `createdAt` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);

-- AlterTable
ALTER TABLE `Payments` MODIFY `createdAt` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);

-- AlterTable
ALTER TABLE `Users` MODIFY `createdAt` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
