-- AlterTable
ALTER TABLE `Customers` MODIFY `createdAt` DATETIME(6) NOT NULL DEFAULT CONVERT_TZ(NOW(), '+00:00', '-03:00');

-- AlterTable
ALTER TABLE `Payments` MODIFY `createdAt` DATETIME(6) NOT NULL DEFAULT CONVERT_TZ(NOW(), '+00:00', '-03:00');

-- AlterTable
ALTER TABLE `Users` MODIFY `createdAt` DATETIME(6) NOT NULL DEFAULT CONVERT_TZ(NOW(), '+00:00', '-03:00');
