-- AlterTable
ALTER TABLE `Customers` MODIFY `due_date` DATETIME(6) NOT NULL,
    MODIFY `createdAt` DATETIME(6) NOT NULL DEFAULT (NOW() - INTERVAL 3 HOUR),
    MODIFY `updatedAt` DATETIME(6) NOT NULL;

-- AlterTable
ALTER TABLE `Payments` MODIFY `createdAt` DATETIME(6) NOT NULL DEFAULT (NOW() - INTERVAL 3 HOUR),
    MODIFY `updatedAt` DATETIME(6) NOT NULL;

-- AlterTable
ALTER TABLE `Users` MODIFY `createdAt` DATETIME(6) NOT NULL DEFAULT (NOW() - INTERVAL 3 HOUR),
    MODIFY `updatedAt` DATETIME(6) NOT NULL;
